### ISSUE TITLE
Usage of "esbuild" package fails to find it's os-specific counterpart. 

### ISSUE THREAD

**Issue by nicksrandall** [vercel/nft#246]
I would expect that if I was using a linux machine that and requiring "esbuild" into my project that "esbuild-linux-64" would also be listed as a needed dependency.

**Comment by styfle** [comment]
Its likely caused by `esbuild` using a dynamic require so `nft` can't statically analyze

https://github.com/evanw/esbuild/blob/11d7eacd491c94d2aa23cd7d48ffd9195f26c108/lib/npm/node-platform.ts#L74

There was [a thread](https://twitter.com/Brooooook_lyn/status/1458098687809359879) where `napi-rs` had a similar issue and changing to a more [static solution](https://github.com/napi-rs/napi-rs/pull/845) fixed it.

I suggest that `esbuild` do the same.

**Comment by styfle** [comment]
Looks like this is a common issue so we can add a special case for `esbuild`

- https://github.com/vercel/vercel/issues/7287
- https://github.com/vercel/next.js/issues/33294
