### ISSUE TITLE
Please add support for `envkey`

### ISSUE THREAD

**Issue by shamoons** [vercel/nft#47]
https://github.com/envkey/envkey-node

For some reason, it doesn't pick up on the binaries needed. Presently the integration test:
```
require('envkey')
```

fails with
```
  ● should correctly trace and correctly execute envkey.js

    expect(received).toBe(expected) // Object.is equality

    Expected: 0
    Received: 1

      51 |     });
      52 |     const code = await new Promise(resolve => ps.on('close', resolve));
    > 53 |     expect(code).toBe(fails ? 1 : 0);
         |                  ^
      54 |     rimraf.sync(tmpdir);
      55 |   });
      56 | }
```

**Comment by styfle** [comment]
Hi @shamoons 

With [ZEIT Now](https://zeit.co/now), you don't need to include this package because this feature is built into the platform.

You can add [secrets and environment variables](https://zeit.co/docs/v2/serverless-functions/env-and-secrets) to a team/personal account and then these will be made available securely during `now` cloud deployments as well as `now dev` for local development.

The [envkey](https://packagephobia.now.sh/result?p=envkey) package is over the 50MB limit so it likely won't work anyway.

**Comment by shamoons** [comment]
@styfle `now -e` is pretty cool. But when there are many secrets (20-50), it gets very cumbersome to have to reproduce in `now.json`, `build`, etc. I believe @danenania is working on reducing the file size. I forked it and removed the unnecessary binaries: https://github.com/shamoons/envkey-node

**Comment by styfle** [comment]
Sounds like the fork will solve the issue then? I'll go ahead and close this 👍
